---
title: "Project Proposal"
author: "Mario Alvarez"
date: "3/21/2021"
output:
  pdf_document: default
  html_document: default
---

```{r packages}
library(tidyverse)
library(infer)
library(dplyr)
```

```{r data-cleanup-labor}
labordats <- read.csv(file = 'data/LaborNEconomy.csv')%>%
  select(-T16, -X.4)%>%
  slice(2:n())

val <- as.numeric(labordats$X.2)

labordats <- labordats%>%
  select(-X.2)%>%
  mutate(X.5 = val)

names(labordats)[names(labordats) == "X"] <- "Year"
names(labordats)[names(labordats) == "X.1"] <- "Statistic"
names(labordats)[names(labordats) == "X.5"] <- "Rates"
names(labordats)[names(labordats) == "X.3"] <- "Type"
names(labordats)[names(labordats) == 
                   "Labour.force.participation.and.unemployment"] <- "Region"


view(labordats)
```

```{r data-cleanup-govt}
womengovt <- read.csv(file = 'data/WomenInGovt.csv')%>%
  slice(2:n())%>%
  select(-X.1, -X.2, -X.3, -X.5, -X.6, -T04)

  names(womengovt)[names(womengovt) == "X"] <- "Year"
  names(womengovt)[names(womengovt) == "X.4"] <- "Proportion of Women in Govt"
  names(womengovt)[names(womengovt) == 
                     "Proportion.of.seats.held.by.women.in.national.parliament"] <- "Region"
laborngovt <- right_join(labordats, womengovt)
```

```{r data-cleanup-edu}
womenedu <- read.csv(file = 'data/WomenEdu.csv')%>%
  slice(2:n())%>%
  select(-X.3, -X.4, -T05)

  names(womenedu)[names(womenedu) == "X"] <- "Year"
  names(womenedu)[names(womenedu) == "X.1"] <- "EducationLevel"
  names(womenedu)[names(womenedu) == "X.2"] <- "Gender Ratio Temp"
  names(womenedu)[names(womenedu) == 
                     "Ratio.of.girls.to.boys.in.primary..secondary.and.tertiary.education"] <- "Region"

ratiov <- as.numeric(womenedu$"Gender Ratio Temp")

womenedu <- womenedu %>%
  mutate(GenderRatio = ratiov)%>%
  select(-"Gender Ratio Temp")
```

```{r data-cleanup-ineq}
genderineq <- read.csv(file = 'data/GenderIneq.csv')%>%
  slice(6:189)%>%
  select(X.1, X.2, SDG3.7, SDG3.1)

ineq <- as.numeric(genderineq$X.2)
birthr <- as.numeric(genderineq$SDG3.7)
mortalr <- as.numeric(genderineq$SDG3.1)

genderineq <- genderineq%>%
  mutate(GenderIneqIndex = ineq, TeenBirthRate = birthr,
         MaternalMortality = mortalr)%>%
  select(-X.2, -SDG3.7, -SDG3.1)

names(genderineq)[names(genderineq) == "X.1"] <- "Region"
```



```{r data-cleanup-joined-1}
prop <- as.numeric(laborngovt$"Proportion of Women in Govt")
laborngovt <- laborngovt%>%
  mutate("PropOfWomen" = prop)%>%
  select(-"Proportion of Women in Govt")

laborgender <- right_join(laborngovt, womenedu)%>%
  view()
```

```{r final-data-cleanup}
laborgender <- left_join(laborgender, genderineq)%>%
  view()
```

```{r dataset-sharpener}
laborgender <- laborgender%>%
  filter(Statistic != "Unemployment rate - Total",
         Statistic != "Unemployment rate - Male",
         Statistic != "Unemployment rate - Female")%>%
  select(-Type)%>%
  view()
```



```{r women-particip, fig.width = 9, fig.height = 8}
laborgender %>%
  filter(Statistic == "Labour force participation - Female", Year == "2015")%>%
  slice(1:32)%>%
  ggplot(mapping = aes(x = Region, y = Rates))+
  geom_bar(stat = "identity", fill = "#521173")+
  coord_flip()+
  scale_y_continuous(limits = c(0,100))+
  scale_x_discrete(limits = rev)+
  labs(title = "Labor force participation of women around the world",
       subtitle = "By region", x = "Region",
       y = "Labor force participation rate (%)")
```


```{r particip-versus-prop}
laborgender%>%
  filter(Year == "2015", Statistic == "Labour force participation - Female",
         EducationLevel == "Ratio of girls to boys in tertiary education")%>%
  ggplot(mapping = aes(x = GenderRatio, y = Rates))+
  geom_point()+
  geom_smooth(se = FALSE)+
  scale_y_continuous(limits = c(0,100))+
  scale_x_continuous(limits = c(0,2))+
  labs(title = "Labor force participation of women vs. their educational opportunities",
       subtitle = "Without Qatar",
       x = "Ratio of women to men in tertiary education",
       y= "Labor force participation of women (%)")
```
```{r only-labor}
laborgender%>%
  filter(Year == "2015", 
        Statistic == "Labour force participation - Female")%>%
  slice(23:n())%>%
  ggplot(mapping = aes(x = Rates))+
  geom_density(size = 2, fill = "black", alpha = 0.4)+
  scale_x_continuous(limits = c(0,100))
```


```{r correlations}
womenedu2 <- laborgender %>%
  filter(Year == "2015", Statistic == "Labour force participation - Female",
         EducationLevel == "Ratio of girls to boys in secondary education")%>%
  select(GenderRatio, Rates)
  cor.test(womenedu2$GenderRatio, womenedu2$Rates, method = "spearman")
```